### ISSUE TITLE
SEMANA 1 - CLASE 1 LABORATORIO_USUARIO : Scrum master Carlos Pereira en Python, Java, Javascript y Node

### ISSUE THREAD

**Issue by Vera2376** [CodeSystem2022/Uritorco_UTN_Cuarto_Semestre_2023#2]

**Comment by Vera2376** [comment]
En la clase 1 vemos en Python : Clase usuario DAO.
Clase 1 en Java : Creamos el main, Sistema estudiante app
Clase 2 en Javascript : Avanzamos con CCS.
Node : Instalación de NODE, vemos la información importante y necesaria.

**Comment by 1984hats** [comment]
realizado =)
