### ISSUE TITLE
Asignación de tareas : CLASE 1 Verónica Díaz en Phyton, Java, Javascript y NODE.

### ISSUE THREAD

**Issue by Vera2376** [CodeSystem2022/Uritorco_UTN_Cuarto_Semestre_2023#3]

**Comment by Vera2376** [comment]
Phyton : Clase 1 base de datos, Postgresql, clase entidad usuario.
Java : Clase 1 : Método eliminar estudiante y prueba
Javascript : Comenzamos con el proyecto, código HTML y CSS
NODE : Instalación de Node e información importante y necesaria.

**Comment by 1984hats** [comment]
Listo !!!
